[package]
name = "tree-sitter-p"
description = "P is a state machine based programming language for formally modeling and specifying complex distributed systems."
version = "0.1.0"
authors = ["Byron Batteson <byronbatteson@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "p"]
categories = ["parser-implementations", "parsing", "text-editors"]
repository = "https://github.com/battesonb/tree-sitter-p"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "tree-sitter.json",
  "/LICENSE",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.26.8"
